apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/part-of: finpay-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.17.0
          ports:
            - containerPort: 9200
            - containerPort: 9600
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: "Finpay!Lab#2026"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms256m -Xmx384m"
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: {cpu: 250m, memory: 512Mi}
            limits: {cpu: 1, memory: 1Gi}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9600
      targetPort: 9600
